<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Step1]]>
    </line>
    <line>
      <![CDATA[Step2]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="50" started-at="2017-10-14T04:02:03Z" finished-at="2017-10-14T04:02:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="50" started-at="2017-10-14T04:02:03Z" finished-at="2017-10-14T04:02:03Z">
      <class name="com.Day13.Day13_1">
        <test-method status="FAIL" signature="Test12()[pri:0, instance:com.Day13.Day13_1@6a2bcfcb]" name="Test12" duration-ms="19" started-at="2017-10-14T09:32:03Z" finished-at="2017-10-14T09:32:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [xyz] but found [abc]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [xyz] but found [abc]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.Day13.Day13_1.Test12(Day13_1.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Step1]]>
            </line>
            <line>
              <![CDATA[Step2]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test12 -->
      </class> <!-- com.Day13.Day13_1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
